version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: student_uni_mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=student_uni_system_2
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/student_uni_system_2
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: npm run dev
    depends_on:
      - mongodb
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  mongodb_data:
